app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView, RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("newsletter/", include("newsletter.urls")),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    # path('', RedirectView.as_view(url='newsletter/', permanent=True)),
]

members/urls.py
from django.urls import path
from . import views


app_name = "members"
urlpatterns = [
    path('login_user', views.login_user, name="login_user"),
    path('logout_user', views.logout_user, name='logout_user'),
    path('register_user', views.register_user, name='register_user'),
    path('change_password', views.change_password, name="change_password"),
    path('reset_password', views.reset_password, name="reset_password"),
    path('delete_user', views.delete_user, name="delete_user"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

# Added by default
# members/login/ [name='login']
# members/logout/ [name='logout']
# members/password_change/ [name='password_change']
# members/password_change/done/ [name='password_change_done']
# members/password_reset/ [name='password_reset']
# members/password_reset/done/ [name='password_reset_done']
# members/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# members/reset/done/ [name='password_reset_complete']

newsletter/urls.py
from django.urls import path
from . import views

app_name = "newsletter"
urlpatterns = [
    path("", views.home, name="home"),
    path("filters", views.filters, name="filters"),
    path("listings", views.listings, name="listings"),
    path("settings", views.settings, name="settings"),
    path("send_mail", views.send_aggregated_daily_newsletters, name="send_mail"),
]

newsletter/models.py
from django.db import models
from members.models import CustomUser
from datetime import date
from django.core.validators import MinValueValidator, MaxValueValidator


class Neighbourhood(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class LengthOfStayOption(models.Model):
    duration = models.IntegerField(unique=True)
    label = models.CharField(max_length=10)

    def __str__(self):
        return self.label

class GenderOption(models.Model):
    gender = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.gender
    

class User_Filter(models.Model):
    price_limit = models.IntegerField(
        default=None, null=True, blank=True,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(8100) 
        ]
    )
    no_price_limit = models.BooleanField(default=None, null=True, blank=True)

    personal_bathroom = models.BooleanField(default=False)
    full_place = models.BooleanField(default=False)
    furnished = models.BooleanField(default=False)
    min_beds = models.IntegerField(default=None, null=True, blank=True)
    max_beds = models.IntegerField(default=None, null=True, blank=True)
    min_baths = models.IntegerField(default=None, null=True, blank=True)
    max_baths = models.IntegerField(default=None, null=True, blank=True)
    
    move_in_date = models.DateField(default=None, null=True, blank=True)

    length_of_stay = models.ManyToManyField(LengthOfStayOption, blank=True)
    gender = models.ManyToManyField(GenderOption, blank=True)
    neighbourhoods = models.ManyToManyField(Neighbourhood, blank=True)

    def __str__(self):
        return f"USER=price:{self.price_limit} - beds:{self.min_beds} - baths:{self.min_baths} - furnished:{self.furnished} - full_place:{self.full_place} - personal_bath:{self.personal_bathroom} - gender:{self.gender.all()} - move_in:{self.move_in_date} - length_of_stay:{self.length_of_stay}"



class Listing_Parameters(models.Model):
    price = models.IntegerField(default=0)
    move_in_date = models.DateField(default=date.today)
    length_of_stay = models.ManyToManyField(LengthOfStayOption, blank=True)
    num_baths = models.IntegerField(default=0)
    num_beds = models.IntegerField(default=0) 
    furnished = models.BooleanField(default=False)
    full_place = models.BooleanField(default=False)
    personal_bathroom = models.BooleanField(default=False)
    gender = models.ManyToManyField(GenderOption, blank=True)
    neighbourhood = models.ForeignKey(Neighbourhood, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"LISTING=price:{self.price} - beds:{self.num_beds} - baths:{self.num_baths} - furnished:{self.furnished} - full_place:{self.full_place} - personal_bath:{self.personal_bathroom} - gender:{self.gender.all()} - hood:{self.neighbourhood}"
    

class Listing(models.Model):
    title = models.CharField(max_length=500)
    link = models.CharField(max_length=200, null=True) 
    potential_spam = models.BooleanField(default=False)
    pub_date = models.DateTimeField("date published", null=True)
    parameters = models.OneToOneField(Listing_Parameters, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    listings = models.ManyToManyField(Listing, blank=True)
    filter = models.OneToOneField(
        User_Filter,
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        # Use the email field for the string representation
        return self.user.email
    

newsletter/forms.py
from django import forms
from .models import User_Filter, Neighbourhood
from .widgets import RangeInput


class FilterForm(forms.ModelForm):
    min_beds = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': 'Min', 'class': 'form-control', 'min': '0'}),
        min_value=0,  # Ensures the value is not negative on the server side
        required=False  # Adjust based on whether a value is required
    )
    max_beds = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': 'Max', 'class': 'form-control', 'min': '0'}),
        min_value=0,  # Server-side validation for non-negative values
        required=False
    )
    min_baths = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': 'Min', 'class': 'form-control', 'min': '0'}),
        min_value=0,  # Ensures the value is not negative on the server side
        required=False  # Adjust based on whether a value is required
    )
    max_baths = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': 'Max', 'class': 'form-control', 'min': '0'}),
        min_value=0,  # Server-side validation for non-negative values
        required=False
    )

    class Meta:
        model = User_Filter
        fields = ['no_price_limit', 'price_limit', 'min_beds', 'max_beds', 'min_baths', 'max_baths', 'gender', 'personal_bathroom', 'full_place', 'furnished', 'neighbourhoods', 'move_in_date', 'length_of_stay']
        widgets = {
            'neighbourhoods': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'price_limit': RangeInput(attrs={'class': 'my-custom-class'}),
            'move_in_date': forms.DateInput(attrs={'type': 'date'}),
            'length_of_stay': forms.CheckboxSelectMultiple,
            'gender': forms.CheckboxSelectMultiple,
        }

    def __init__(self, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        self.fields['price_limit'].label = 'Price Limit'
        self.fields['gender'].label = 'Gender Preference'
        self.fields['furnished'].label = 'Furnished'
        self.fields['full_place'].label = 'Full Place To Yourself'


    # TODO: not sure if this is the correct way to save no_price_limit if price is at max
    def save(self, commit=True):
        model_instance = super(FilterForm, self).save(commit=False)
        if self.cleaned_data['price_limit'] > 8000:
            self.fields['no_price_limit'] = True
        if commit:
            model_instance.save()

        return model_instance
    

newsletter/views.py
from django.http import HttpResponse
from members.models import CustomUser
from .models import UserProfile, User_Filter, Listing, Neighbourhood
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import FilterForm
from django.contrib.auth.forms import UserCreationForm

from django.utils.timezone import now, timedelta
from django.core.mail import send_mail

from django.utils import timezone


from .helpers import get_matching_listings, matches_user_filter, min_max_beds_baths_init_set, send_aggregated_newsletter

import json

from collections import defaultdict


def home(request):
    return render(request, 'home.html', {"form": UserCreationForm()})

def filters(request):
    # Redirect unauthenticated users
    if not request.user.is_authenticated:
        return redirect('members:login_user')
    
    user_profile = get_object_or_404(UserProfile, user=request.user)

    if user_profile.filter:
        user_filter = user_profile.filter
        created = False
    else:
        # Create a new User_Filter instance and associate it with the UserProfile
        user_filter = User_Filter.objects.create()
        user_profile.filter = user_filter
        user_profile.save()
        created = True


    # user_profile, _ = UserProfile.objects.get_or_create(user=request.user)
    # user_filter: User_Filter = getattr(user_profile, 'filter', None)
    # user_filter, created = User_Filter.objects.get_or_create(userprofile=user_profile)



    if request.method == 'POST':
        form = FilterForm(request.POST, instance=user_filter)
        if form.is_valid():
            if not created:
                # If an existing filter was found, delete any other filters this user might have.
                User_Filter.objects.filter(userprofile=user_profile).exclude(pk=user_filter.pk).delete()

            user_filter = form.save(commit=False)
            form.save_m2m()  # Needed for saving ManyToMany fields if commit=False
            
            # forcing default values on save if they are not set
            # TODO: figure out how to set them as default without overwriting the placeholders
            min_max_beds_baths_init_set(user_filter)

            user_filter.save()

            user_profile.filter = user_filter
            user_profile.save()
            
            
            messages.success(request, "Filter Updated!")
            return redirect('newsletter:filters')
        else:
            messages.error(request, "Something went wrong with the form...")  # Use messages.error for errors
    else:
        form = FilterForm(instance=user_filter)

    user_neighbourhoods = list(user_filter.neighbourhoods.values('id', 'name')) if user_filter else []
    context = {
        "form": form,
        "all_neighbourhoods": Neighbourhood.objects.all(),
        "user_neighbourhoods": json.dumps(user_neighbourhoods),
        "user_price_limit": json.dumps(user_filter.price_limit if user_filter else 0),
    }

    if request.is_mobile:
        return render(request, "newsletter/mobile/mobile_filter.html", context)
    return render(request, "newsletter/filters.html", context)

def listings(request):
    user_profile, _ = UserProfile.objects.get_or_create(user=request.user)
    user_filter = getattr(user_profile, 'filter', None)

    # Default to 'month' if 'timeframe' is not specified in the GET request
    selected_timeframe = request.GET.get('timeframe', 'month')
    
    # Define the timedelta for each timeframe
    delta = {
        'day': timedelta(days=1),
        'week': timedelta(weeks=1),
        'month': timedelta(days=30)
    }

    # Filter listings based on the selected timeframe
    if selected_timeframe in delta:
        time_threshold = now() - delta[selected_timeframe]
        listings = get_matching_listings(user_filter, Listing.objects.filter(pub_date__gte=time_threshold))
    else:
        listings = Listing.objects.all()

    # Pass the selected timeframe to the template via context
    context = {
        'listings': listings,
        'selected_timeframe': selected_timeframe
    }
    return render(request, 'newsletter/listings.html', context)

def settings(request):
    return render(request, 'newsletter/settings.html')

from django.contrib.auth.decorators import login_required, user_passes_test

def is_admin_user(user):
    return user.is_authenticated and user.is_superuser

@login_required
@user_passes_test(is_admin_user)
def send_aggregated_daily_newsletters(request):
    # Step 1: Fetch Listings from the past 24 hours
    yesterday = timezone.now() - timedelta(days=1)
    recent_listings = Listing.objects.filter(pub_date__gte=yesterday)

    all_listings = Listing.objects.all()
    # Initialize a dictionary to hold matching listings for each user
    user_listings_map = defaultdict(list)

    # Iterate through each user profile instead of each listing
    user_profiles = UserProfile.objects.all()
    for user_profile in user_profiles:
        for listing in all_listings:
            if matches_user_filter(user_profile.filter, listing.parameters):
                user_listings_map[user_profile.user.email].append(listing)

    # Step 2: Send a single Newsletter to each user with all matching listings
    print(user_profiles)
    for user_email, listings in user_listings_map.items():
        send_aggregated_newsletter(user_email, listings)
    
    return HttpResponse("Emails sent successfully")

newsletter/templates/newsletter/filters.html
{% extends "profile_base.html" %}
{% block breadcrumb %}
<h3 class="card-title mb-4">Update Your Preferences</h3>
  {% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
  </div>
  {% endif %}
  
  
  <form action="{% url 'newsletter:filters' %}" method="post" class="form-filter">
    {% csrf_token %}

    <div class="form-filter-grouping">
      <div class="form-group col">

        <!-- Price Selection -->
        <div class="form-group row d-flex align-items-center" style="margin: 0px;">
          <label for="{{ form.price_limit.id_for_label }}" class="col-sm-2 col-form-label">{{ form.price_limit.label }}</label>
          <div class="col-sm-6">
                {{ form.price_limit }} <span id="{{ form.price_limit.id_for_label }}_value"></span>
          </div>
        </div>

        <!-- Bedroom Selection -->
        <div class="form-group row d-flex align-items-center" style="margin: 0px;">
          <label class="col-sm-2 col-form-label">Beds</label>
          <div class="col-sm-5">
            <div style="display: flex; ">{{ form.min_beds }}<p style="margin: 5px 20px 0px 20px; ">-</p>{{ form.max_beds }}</div>
          </div>
        </div>

        <!-- Bathroom Selection -->
        <div class="form-group row d-flex align-items-center" style="margin: 0px;">
          <label class="col-sm-2 col-form-label">Baths</label>
          <div class="col-sm-5">
            <div style="display: flex; ">{{ form.min_baths }}<p style="margin: 5px 20px 0px 20px; ">-</p>{{ form.max_baths }}</div>
          </div>
        </div>
      
        <!-- Move In Date Selection -->
        <div class="form-group row d-flex align-items-center" style="margin: 0px;">
            <label for="{{ form.move_in_date.id_for_label }}" class="col-sm-2 col-form-label">{{ form.move_in_date.label }}</label>
            <div class="col-sm-6">
                {{ form.move_in_date }}
            </div>
        </div>

        <!-- Length Of Stay Selection -->
        {% load widget_tweaks %}
        <div class="form-group row d-flex align-items-center" style="margin: 0px;">
          <div class="btn-group btn-group-toggle" data-toggle="buttons">
            {% for choice in form.length_of_stay.field.choices %}
                <label class="btn btn-outline-primary">
                    <input type="checkbox" name="{{ form.length_of_stay.name }}" id="btncheck_length_{{ forloop.counter }}"
                          value="{{ choice.0 }}"
                          {% if choice.0 in form.length_of_stay.value %}checked{% endif %}
                          autocomplete="off"> {{ choice.1|capfirst }}
                </label>
            {% endfor %}
          </div>
        </div>

        <!-- Gender Selection -->
        <div class="form-group row d-flex align-items-center" style="margin: 0px;">
          <div class="btn-group btn-group-toggle" data-toggle="buttons">
              {% for choice in form.gender.field.choices %}
                  <label class="btn btn-outline-primary">
                      <input type="checkbox" name="{{ form.gender.name }}" id="btncheck_gender_{{ forloop.counter }}"
                          value="{{ choice.0 }}"
                          {% if choice.0 in form.gender.value %}checked{% endif %}
                          autocomplete="off"> {{ choice.1|capfirst }}
                  </label>
              {% endfor %}
          </div>
        </div>

        <!--Other Checkbox Selection -->
        <div class="btn-group-toggle" data-toggle="buttons">
          <label class="btn btn-outline-primary {% if form.personal_bathroom.value %}active{% endif %}">
              <input type="checkbox" id="{{ form.personal_bathroom.id_for_label }}" name="{{ form.personal_bathroom.name }}" autocomplete="off" {% if form.personal_bathroom.value %}checked{% endif %}>
              {{ form.personal_bathroom.label }}
          </label>
          <label class="btn btn-outline-primary {% if form.full_place.value %}active{% endif %}">
              <input type="checkbox" id="{{ form.full_place.id_for_label }}" name="{{ form.full_place.name }}" autocomplete="off" {% if form.full_place.value %}checked{% endif %}>
              {{ form.full_place.label }}
          </label>
          <label class="btn btn-outline-primary {% if form.furnished.value %}active{% endif %}">
              <input type="checkbox" id="{{ form.furnished.id_for_label }}" name="{{ form.furnished.name }}" autocomplete="off" {% if form.furnished.value %}checked{% endif %}>
              {{ form.furnished.label }}
          </label>
        </div>
      </div>

      <!-- Neighbourhoods Selection -->
      <select id="id_neighbourhoods" multiple="multiple" name="neighbourhoods" style="display:none;">
        {% for neighbourhood in form.neighbourhoods.field.queryset %}
            <option value="{{ neighbourhood.id }}">{{ neighbourhood.name }}</option>
        {% endfor %}
      </select>

      <!-- Custom rendering for 'neighbourhoods' -->
      <div class="form-group col">
        <h5>Neighbourhoods</h5>
        <div class="scrollable-container">
          <div class="btn-group-toggle" data-toggle="buttons">
            {% for neighbourhood in form.neighbourhoods.field.queryset %}
            <label class="btn btn-outline-primary hood" for="btncheck_hood_{{ neighbourhood.id }}">
                <input type="checkbox" class="btn-check" autocomplete="off" id="btncheck_hood_{{ neighbourhood.id }}" value="{{ neighbourhood.id }}"> {{ neighbourhood.name }}
            </label>
            {% endfor %}
          </div>
        </div>
      </div>
      {% comment %} <div class="form-group col">
        <div id="mapid"></div>
      </div> {% endcomment %}

    </div>
    
    <div class="mt-3">
      <button type="submit" class="btn btn-primary bg-success">Update</button>
    </div>
  </form>
{% endblock %}

newsletter/templates/newsletter/listings.html
{% extends "profile_base.html" %}

{% block breadcrumb %}
<h3 class="card-title mb-4">Matched Listings</h3>
    <form action="{% url 'newsletter:listings' %}" method="GET" id="timeframeForm">
        <select name="timeframe" class="form-select" onchange="this.form.submit()">
            <option value="day" {% if selected_timeframe == 'day' %}selected{% endif %}>Today</option>
            <option value="week" {% if selected_timeframe == 'week' %}selected{% endif %}>Past Week</option>
            <option value="month" {% if selected_timeframe == 'month' %}selected{% endif %} >Past Month</option>
        </select>
    </form>
</br>

{% if listings %}
<ul>
    {% for listing in listings %}
        <li>{{ listing.title }}</li>
    {% endfor %}
</ul>
{% else %}
    <p>No listings found...</p>
{% endif %}
{% endblock %}

newsletter/templates/newsletter/load_neighbourhood_data_script.html
<script>
$(document).ready(function () {
$(".btn").click(function(event) {
    // Removes focus of the button.
    $(this).blur();
});
}); 
document.addEventListener('DOMContentLoaded', (event) => {
    let savedNeighborhoods = [];
    try {
        savedNeighborhoods = JSON.parse('{{ user_neighbourhoods|safe }}');
    } catch (error) {
        console.error('Failed to parse neighborhoods:', error);
    }
    const savedNeighborhoodIDs = savedNeighborhoods.map((neighborhood) => neighborhood.id);
    
    document.querySelectorAll('.btn-check').forEach(checkbox => {
        // Check if the checkbox should be checked based on saved neighborhoods
        const checkboxValue = parseInt(checkbox.value, 10);
        if (savedNeighborhoodIDs.includes(checkboxValue)) {
            checkbox.checked = true;
            const label = document.querySelector(`label[for="${checkbox.id}"]`);
            if (label) {
                label.classList.add('active');
            }
        }

        // Listen for changes directly on the checkbox
        checkbox.addEventListener('change', () => {
            const label = document.querySelector(`label[for="${checkbox.id}"]`);
            if (checkbox.checked) {
                label.classList.add('active');
            } else {
                label.classList.remove('active');
            }
            syncCheckboxes();
        });
    });

    // Initial sync to ensure select matches checkboxes
    syncCheckboxes();
});

function syncCheckboxes() {
    let selectedOptions = [];
    document.querySelectorAll('.btn-check:checked').forEach(checkbox => {
        selectedOptions.push(checkbox.value);
    });

    let select = document.getElementById('id_neighbourhoods');
    Array.from(select.options).forEach(option => {
        option.selected = selectedOptions.includes(option.value);
    });
}

</script>

newsletter/templates/newsletter/price_range_script.html
<script>
document.addEventListener('DOMContentLoaded', function() {
    const initValue = JSON.parse('{{ user_price_limit|safe }}');
    var slider = document.getElementById("{{ form.price_limit.id_for_label }}");
    var output = document.getElementById("{{ form.price_limit.id_for_label }}_value");

    if (initValue == 8100) {
        output.innerHTML = "No limit"; // Max
    } else {
        output.innerHTML = initValue + "$";
    }

    // Update the output text whenever the slider value changes
    slider.oninput = function() {
        if (this.value == 8100) {
            output.innerHTML = "No limit"; // Max
        } else {
            output.innerHTML = this.value + "$";
        }
    }
});
</script>

newsletter/templates/newsletter/settings.html
{% extends "profile_base.html" %}

{% block breadcrumb %}
<h3 class="card-title mb-4">Settings</h3>
<ul>
    <li><a href="{% url 'members:delete_user' %}">Delete Account</a></li>
    <li><a href="{% url 'password_change' %}">Change Password</a></li>
    <li><a href="{% url 'members:logout_user' %}">Log out</a></li>
</ul>
{% endblock %}