app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView, RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("newsletter/", include("newsletter.urls")),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    # path('', RedirectView.as_view(url='newsletter/', permanent=True)),
]

members/urls.py
from django.urls import path
from . import views


app_name = "members"
urlpatterns = [
    path('login_user', views.login_user, name="login_user"),
    path('logout_user', views.logout_user, name='logout_user'),
    path('register_user', views.register_user, name='register_user'),
    path('change_password', views.change_password, name="change_password"),
    path('reset_password', views.reset_password, name="reset_password"),
    path('delete_user', views.delete_user, name="delete_user"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

# Added by default
# members/login/ [name='login']
# members/logout/ [name='logout']
# members/password_change/ [name='password_change']
# members/password_change/done/ [name='password_change_done']
# members/password_reset/ [name='password_reset']
# members/password_reset/done/ [name='password_reset_done']
# members/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# members/reset/done/ [name='password_reset_complete']

newsletter/urls.py
from django.urls import path
from . import views

app_name = "newsletter"
urlpatterns = [
    path("", views.home, name="home"),
    path("filters", views.filters, name="filters"),
    path("listings", views.listings, name="listings"),
    path("settings", views.settings, name="settings"),
    path("send_mail", views.send_aggregated_daily_newsletters, name="send_mail"),
]

newsletter/models.py
from django.db import models
from members.models import CustomUser
from datetime import date
from django.core.validators import MinValueValidator, MaxValueValidator


class Neighbourhood(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class LengthOfStayOption(models.Model):
    duration = models.IntegerField(unique=True)
    label = models.CharField(max_length=10)

    def __str__(self):
        return self.label

class GenderOption(models.Model):
    gender = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.gender
    

class User_Filter(models.Model):
    price_limit = models.IntegerField(
        default=None, null=True, blank=True,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(8100) 
        ]
    )
    no_price_limit = models.BooleanField(default=None, null=True, blank=True)

    personal_bathroom = models.BooleanField(default=False)
    full_place = models.BooleanField(default=False)
    furnished = models.BooleanField(default=False)
    min_beds = models.IntegerField(default=None, null=True, blank=True)
    max_beds = models.IntegerField(default=None, null=True, blank=True)
    min_baths = models.IntegerField(default=None, null=True, blank=True)
    max_baths = models.IntegerField(default=None, null=True, blank=True)
    
    move_in_date = models.DateField(default=None, null=True, blank=True)

    length_of_stay = models.ManyToManyField(LengthOfStayOption, blank=True)
    gender = models.ManyToManyField(GenderOption, blank=True)
    neighbourhoods = models.ManyToManyField(Neighbourhood, blank=True)

    def __str__(self):
        return f"USER=price:{self.price_limit} - beds:{self.min_beds} - baths:{self.min_baths} - furnished:{self.furnished} - full_place:{self.full_place} - personal_bath:{self.personal_bathroom} - gender:{self.gender.all()} - move_in:{self.move_in_date} - length_of_stay:{self.length_of_stay}"



class Listing_Parameters(models.Model):
    price = models.IntegerField(default=0)
    move_in_date = models.DateField(default=date.today)
    length_of_stay = models.ManyToManyField(LengthOfStayOption, blank=True)
    num_baths = models.IntegerField(default=0)
    num_beds = models.IntegerField(default=0) 
    furnished = models.BooleanField(default=False)
    full_place = models.BooleanField(default=False)
    personal_bathroom = models.BooleanField(default=False)
    gender = models.ManyToManyField(GenderOption, blank=True)
    neighbourhood = models.ForeignKey(Neighbourhood, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"LISTING=price:{self.price} - beds:{self.num_beds} - baths:{self.num_baths} - furnished:{self.furnished} - full_place:{self.full_place} - personal_bath:{self.personal_bathroom} - gender:{self.gender.all()} - hood:{self.neighbourhood}"
    

class Listing(models.Model):
    title = models.CharField(max_length=500)
    link = models.CharField(max_length=200, null=True) 
    potential_spam = models.BooleanField(default=False)
    pub_date = models.DateTimeField("date published", null=True)
    parameters = models.OneToOneField(Listing_Parameters, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    listings = models.ManyToManyField(Listing, blank=True)
    filter = models.OneToOneField(
        User_Filter,
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        # Use the email field for the string representation
        return self.user.email
    

newsletter/forms.py
from django import forms
from .models import User_Filter, Neighbourhood
from .widgets import RangeInput


class FilterForm(forms.ModelForm):
    min_beds = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': 'Min', 'class': 'form-control', 'min': '0'}),
        min_value=0,  # Ensures the value is not negative on the server side
        required=False  # Adjust based on whether a value is required
    )
    max_beds = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': 'Max', 'class': 'form-control', 'min': '0'}),
        min_value=0,  # Server-side validation for non-negative values
        required=False
    )
    min_baths = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': 'Min', 'class': 'form-control', 'min': '0'}),
        min_value=0,  # Ensures the value is not negative on the server side
        required=False  # Adjust based on whether a value is required
    )
    max_baths = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': 'Max', 'class': 'form-control', 'min': '0'}),
        min_value=0,  # Server-side validation for non-negative values
        required=False
    )

    class Meta:
        model = User_Filter
        fields = ['no_price_limit', 'price_limit', 'min_beds', 'max_beds', 'min_baths', 'max_baths', 'gender', 'personal_bathroom', 'full_place', 'furnished', 'neighbourhoods', 'move_in_date', 'length_of_stay']
        widgets = {
            'neighbourhoods': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'price_limit': RangeInput(attrs={'class': 'my-custom-class'}),
            'move_in_date': forms.DateInput(attrs={'type': 'date'}),
            'length_of_stay': forms.CheckboxSelectMultiple,
            'gender': forms.CheckboxSelectMultiple,
        }

    def __init__(self, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        self.fields['price_limit'].label = 'Price Limit'
        self.fields['gender'].label = 'Gender Preference'
        self.fields['furnished'].label = 'Furnished'
        self.fields['full_place'].label = 'Full Place To Yourself'


    # TODO: not sure if this is the correct way to save no_price_limit if price is at max
    def save(self, commit=True):
        model_instance = super(FilterForm, self).save(commit=False)
        if self.cleaned_data['price_limit'] > 8000:
            self.fields['no_price_limit'] = True
        if commit:
            model_instance.save()

        return model_instance
    

newsletter/views.py
from django.http import HttpResponse
from members.models import CustomUser
from .models import UserProfile, User_Filter, Listing, Neighbourhood
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import FilterForm
from django.contrib.auth.forms import UserCreationForm

from django.utils.timezone import now, timedelta
from django.core.mail import send_mail

from django.utils import timezone


from .helpers import get_matching_listings, matches_user_filter, min_max_beds_baths_init_set, send_aggregated_newsletter

import json

from collections import defaultdict


def home(request):
    return render(request, 'home.html', {"form": UserCreationForm()})

def filters(request):
    # Redirect unauthenticated users
    if not request.user.is_authenticated:
        return redirect('members:login_user')
    
    user_profile = get_object_or_404(UserProfile, user=request.user)

    if user_profile.filter:
        user_filter = user_profile.filter
        created = False
    else:
        # Create a new User_Filter instance and associate it with the UserProfile
        user_filter = User_Filter.objects.create()
        user_profile.filter = user_filter
        user_profile.save()
        created = True


    # user_profile, _ = UserProfile.objects.get_or_create(user=request.user)
    # user_filter: User_Filter = getattr(user_profile, 'filter', None)
    # user_filter, created = User_Filter.objects.get_or_create(userprofile=user_profile)



    if request.method == 'POST':
        form = FilterForm(request.POST, instance=user_filter)
        if form.is_valid():
            if not created:
                # If an existing filter was found, delete any other filters this user might have.
                User_Filter.objects.filter(userprofile=user_profile).exclude(pk=user_filter.pk).delete()

            user_filter = form.save(commit=False)
            form.save_m2m()  # Needed for saving ManyToMany fields if commit=False
            
            # forcing default values on save if they are not set
            # TODO: figure out how to set them as default without overwriting the placeholders
            min_max_beds_baths_init_set(user_filter)

            user_filter.save()

            user_profile.filter = user_filter
            user_profile.save()
            
            
            messages.success(request, "Filter Updated!")
            return redirect('newsletter:filters')
        else:
            messages.error(request, "Something went wrong with the form...")  # Use messages.error for errors
    else:
        form = FilterForm(instance=user_filter)

    user_neighbourhoods = list(user_filter.neighbourhoods.values('id', 'name')) if user_filter else []
    context = {
        "form": form,
        "all_neighbourhoods": Neighbourhood.objects.all(),
        "user_neighbourhoods": json.dumps(user_neighbourhoods),
        "user_price_limit": json.dumps(user_filter.price_limit if user_filter else 0),
    }

    if request.is_mobile:
        return render(request, "newsletter/mobile/mobile_filter.html", context)
    return render(request, "newsletter/filters.html", context)

def listings(request):
    user_profile, _ = UserProfile.objects.get_or_create(user=request.user)
    user_filter = getattr(user_profile, 'filter', None)

    # Default to 'month' if 'timeframe' is not specified in the GET request
    selected_timeframe = request.GET.get('timeframe', 'month')
    
    # Define the timedelta for each timeframe
    delta = {
        'day': timedelta(days=1),
        'week': timedelta(weeks=1),
        'month': timedelta(days=30)
    }

    # Filter listings based on the selected timeframe
    if selected_timeframe in delta:
        time_threshold = now() - delta[selected_timeframe]
        listings = get_matching_listings(user_filter, Listing.objects.filter(pub_date__gte=time_threshold))
    else:
        listings = Listing.objects.all()

    # Pass the selected timeframe to the template via context
    context = {
        'listings': listings,
        'selected_timeframe': selected_timeframe
    }
    return render(request, 'newsletter/listings.html', context)

def settings(request):
    return render(request, 'newsletter/settings.html')

from django.contrib.auth.decorators import login_required, user_passes_test

def is_admin_user(user):
    return user.is_authenticated and user.is_superuser

@login_required
@user_passes_test(is_admin_user)
def send_aggregated_daily_newsletters(request):
    # Step 1: Fetch Listings from the past 24 hours
    yesterday = timezone.now() - timedelta(days=1)
    recent_listings = Listing.objects.filter(pub_date__gte=yesterday)

    all_listings = Listing.objects.all()
    # Initialize a dictionary to hold matching listings for each user
    user_listings_map = defaultdict(list)

    # Iterate through each user profile instead of each listing
    user_profiles = UserProfile.objects.all()
    for user_profile in user_profiles:
        for listing in all_listings:
            if matches_user_filter(user_profile.filter, listing.parameters):
                user_listings_map[user_profile.user.email].append(listing)

    # Step 2: Send a single Newsletter to each user with all matching listings
    print(user_profiles)
    for user_email, listings in user_listings_map.items():
        send_aggregated_newsletter(user_email, listings)
    
    return HttpResponse("Emails sent successfully")

newsletter/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Rental Insight{% endblock %}</title>


    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      rel="shortcut icon"
      href="{% static 'newsletter/images/favicon.ico' %}"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'newsletter/css/styles.css' %}?v=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Figtree:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">

    
  </head>
  <body class="d-flex flex-column min-vh-100">
    <header>
      <a href="{% url 'newsletter:home' %}">
        <img
          src="{% static 'newsletter/images/logo.png' %}"
          alt="Logo"
          height="65"
        />
      </a>
      {% if user.is_authenticated %}
        <a href="{% url 'newsletter:filters' %}" class="profile-link">Profile</a>
      {% else %}
        <a href="{% url 'newsletter:filters' %}" class="profile-link">Login</a>
      {% endif %}
      
    </header>
    <main class="flex-shrink-0">
      <div class="container">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-warning" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        {% block content%}{% endblock %}
      </div>
      {% block home_page%}{% endblock %}
    </main>
    <footer class="footer mt-auto py-3 bg-light">
        <div class="container text-center">
            <span class="text-muted">@ Rental Insight</span>
        </div>
    </footer>

    {% include "newsletter/price_range_script.html" %}
    {% include "newsletter/load_neighbourhood_data_script.html" %}
    <!-- Optional JavaScript and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- Map scripts -->
    {% comment %} <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <script type="module" src="{% static 'newsletter/scripts/vancouver_map.js'%}"></script> {% endcomment %}
  </body>
</html>

newsletter/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block home_page %}

<style>
  :root {
    --background-image-url: url('{% static "newsletter/images/rental_building_2.jpg" %}');
  }
</style>


{% if form.errors %}
<div class="alert alert-warning" role="alert">
  There was an error with your sign up... Please try again.
</div>
{% endif %}


<div class="row align-items-center" style="min-height: 80vh; margin: 10px">
    <div class="col-lg-6 text-center" style="margin-bottom: 10px;">
      <h1>Be the first to know about housing in Vancouver!</h1>
      <p class="my-4">
        Looking for housing but tired of scrolling through Facebook groups? Sign up for our newsletter today to get
        instant search results based on exactly what you are looking for.
      </p>
      <a class="btn btn-primary btn-lg" href="{% url 'members:register_user' %}" role="button">Get Exclusive Access</a>
    </div>
    <div class="col-lg-6">
      <div class="image-fade-overlay"></div>
    </div>
  </div>

{% endblock %}

newsletter/templates/profile_base.html
{% extends "base.html" %} 
{% block content %}
<div class="profile-nav">
    <div>Welcome, <b>{{user.email}}</b>!</div>
</div>
<br/>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb" style="background-color: #f8f9fa; margin: 0px; padding-left: 5px;">
    <li class="breadcrumb-item" aria-current="page">
      <a href="{% url 'newsletter:filters' %}">Filters</a>
    </li>
    <li class="breadcrumb-item" aria-current="page">
      <a href="{% url 'newsletter:listings' %}">Listings</a>
    </li>
    <li class="breadcrumb-item" aria-current="page">
      <a href="{% url 'newsletter:settings' %}">Settings</a>
    </li>
  </ol>
</nav>

<div class="card shadow-sm">
    <div class="card-body">
      {% block breadcrumb %}{% endblock%}
    </div>
</div>
{% endblock%}